# Generated by Django 4.0.3 on 2022-03-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_alter_user_actual_name_alter_user_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='moments_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='', max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('thumbs', models.SmallIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=64)),
                ('moments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.moments_info')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='', max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('match_moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.moments_info')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
