# Generated by Django 2.2.4 on 2022-03-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20220323_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='moments_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('thumbs', models.SmallIntegerField(default=0, null=True)),
                ('likes', models.SmallIntegerField(default=0, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=64)),
                ('moments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.moments_info')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('match_moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.moments_info')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
