# Generated by Django 3.2 on 2022-03-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-ctime',)},
        ),
        migrations.AlterModelOptions(
            name='moments_info',
            options={'ordering': ('-ctime',)},
        ),
    ]
