# Generated by Django 4.0.3 on 2022-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moments_info',
            name='likes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
