# Generated by Django 3.2 on 2022-03-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='hasRead',
            field=models.BooleanField(default=True),
        ),
    ]
