# Generated by Django 2.2.4 on 2022-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photo/default.jpg', upload_to='photo/'),
        ),
    ]
