# Generated by Django 3.2.12 on 2022-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='actual_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='photo/default.jpg', upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(default='这个人很神秘，什么都没写', max_length=64, null=True),
        ),
    ]
