# Generated by Django 4.0.2 on 2022-03-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_remove_user_personal_info_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photo/default.jpg', upload_to='photo'),
        ),
    ]
