# Generated by Django 4.0.2 on 2022-03-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_actual_name_alter_user_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actual_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photo/default.jpg', upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(default='这个人很神秘，什么都没写', max_length=64, null=True),
        ),
    ]
