<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-03-20 11:10
=======
# Generated by Django 4.0.3 on 2022-03-14 13:32
>>>>>>> a0c8f50dd391503167ff1aae28936532f3f39e52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_actual_name_alter_user_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
<<<<<<< HEAD
            field=models.ImageField(default='default.jpg', upload_to='photo'),
=======
            field=models.ImageField(default='photo/default.jpg', null=True, upload_to='photo'),
>>>>>>> a0c8f50dd391503167ff1aae28936532f3f39e52
        ),
    ]
