# Generated by Django 4.0.2 on 2022-03-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_actual_name_alter_user_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='photo'),
        ),
    ]
