# Generated by Django 3.2.12 on 2022-03-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='client_header/default.jpg', upload_to='client_header'),
        ),
    ]
