# Generated by Django 4.0.2 on 2022-03-11 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_useraccount_remove_user_personal_info_id_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('following_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_id', to='user.user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user.user')),
            ],
            options={
                'unique_together': {('user_id', 'following_id')},
            },
        ),
    ]
