# Generated by Django 3.2 on 2022-04-05 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_id',
        ),
        migrations.RemoveField(
            model_name='following',
            name='user_id',
        ),
        migrations.AddField(
            model_name='following',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following_id', to='user.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user.userprofile'),
            preserve_default=False,
        ),
    ]
